enable: true
allowSub: false
allowMultiSpin: false
use_db: true
coin:
  material: GOLD_NUGGET
  cmd: 1

mysql:
  host: 'localhost'
  user: 'root'
  pass: 'minecraft'
  port: 3306
  db: 'man10_slot_v2'