name: Man10SlotMachine
version: 1.1.0
main: ltotj.minecraft.man10slotmachine.Main
api-version: 1.17
depend:
  - Vault
softdepend:
  - Man10CommonLibs
commands:
  mslotv2:
    usage: ""

permissions:
  mslotv2.use:
    default: true
  mslotv2.op:
    default: op